apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app-deployment
  namespace: dev
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
        - name: dev-app-container
          image: rrodriguez4570/devops-automation:dev  # Replace with your Docker image for the development environment
          imagePullPolicy: Always
          ports:
            - containerPort: 80

#test